require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin//*
    - db//*
    - node_modules//*
    - vendor//*
    - spec/fixtures//*
    - tmp//*
    - config/environments/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*